#!/usr/bin/env bash

# A startup script to initialise a new sentry installation and setup the default user
set -o errexit
set -o nounset

if [[ -n "${SENTRY_ADMIN_PASSWORD_ENCRYPTED:-""}" ]]; then 
    SENTRY_ADMIN_PASSWORD="$(python /admin_decrypt.py)"
fi

#Run Upgrade/Migration 
sentry upgrade --noinput 

#Create default admin user
# NOTE Password can not be reset using this process this is intended for a run once user setup
user_status=0
sentry permissions list --user "${SENTRY_ADMIN_EMAIL}" || user_status=$? 

if [[ "${user_status}" != 0 ]]; then
    sentry createuser --no-input --email "${SENTRY_ADMIN_EMAIL}" --password "${SENTRY_ADMIN_PASSWORD}" --superuser 
else
    echo "user ${SENTRY_ADMIN_EMAIL} already exists"
fi